# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InstallWizard.ui'
#
# Created: Thu Aug 20 11:47:08 2009
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_InstallWizard(object):
    def setupUi(self, InstallWizard):
        InstallWizard.setObjectName("InstallWizard")
        InstallWizard.resize(537, 391)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Logos/hv.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InstallWizard.setWindowIcon(icon)
        InstallWizard.setWizardStyle(QtGui.QWizard.AeroStyle)
        InstallWizard.setPixmap(QtGui.QWizard.LogoPixmap, QtGui.QPixmap(":/Logos/color.png"))
        InstallWizard.setOptions(QtGui.QWizard.DisabledBackButtonOnLastPage|QtGui.QWizard.IndependentPages)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.verticalLayoutWidget = QtGui.QWidget(self.wizardPage1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, -40, 521, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.introVBox = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.introVBox.setObjectName("introVBox")
        self.greetingMsg = QtGui.QLabel(self.verticalLayoutWidget)
        self.greetingMsg.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.greetingMsg.setWordWrap(True)
        self.greetingMsg.setIndent(13)
        self.greetingMsg.setOpenExternalLinks(True)
        self.greetingMsg.setObjectName("greetingMsg")
        self.introVBox.addWidget(self.greetingMsg)
        InstallWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.wizardPage2)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 521, 271))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.p2Outer = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.p2Outer.setObjectName("p2Outer")
        self.p2Desc = QtGui.QLabel(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2Desc.sizePolicy().hasHeightForWidth())
        self.p2Desc.setSizePolicy(sizePolicy)
        self.p2Desc.setMinimumSize(QtCore.QSize(0, 70))
        self.p2Desc.setWordWrap(True)
        self.p2Desc.setObjectName("p2Desc")
        self.p2Outer.addWidget(self.p2Desc)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.dbTypeLbl = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.dbTypeLbl.setIndent(20)
        self.dbTypeLbl.setObjectName("dbTypeLbl")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.dbTypeLbl)
        self.dbadminUserNameLbl = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.dbadminUserNameLbl.setIndent(20)
        self.dbadminUserNameLbl.setObjectName("dbadminUserNameLbl")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.dbadminUserNameLbl)
        self.dbadminUserName = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbadminUserName.sizePolicy().hasHeightForWidth())
        self.dbadminUserName.setSizePolicy(sizePolicy)
        self.dbadminUserName.setObjectName("dbadminUserName")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.dbadminUserName)
        self.dbType = QtGui.QWidget(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbType.sizePolicy().hasHeightForWidth())
        self.dbType.setSizePolicy(sizePolicy)
        self.dbType.setMinimumSize(QtCore.QSize(0, 50))
        self.dbType.setBaseSize(QtCore.QSize(0, 0))
        self.dbType.setObjectName("dbType")
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.dbType)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 381, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtGui.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.dbType)
        self.dbadminPasswordLbl = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.dbadminPasswordLbl.setIndent(20)
        self.dbadminPasswordLbl.setObjectName("dbadminPasswordLbl")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.dbadminPasswordLbl)
        self.dbadminPassword = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbadminPassword.sizePolicy().hasHeightForWidth())
        self.dbadminPassword.setSizePolicy(sizePolicy)
        self.dbadminPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.dbadminPassword.setObjectName("dbadminPassword")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.dbadminPassword)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtGui.QFormLayout.FieldRole, spacerItem)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtGui.QFormLayout.FieldRole, spacerItem1)
        self.p2Outer.addLayout(self.formLayout)
        InstallWizard.addPage(self.wizardPage2)
        self.wizardPage3 = QtGui.QWizardPage()
        self.wizardPage3.setObjectName("wizardPage3")
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.wizardPage3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 521, 271))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.p3Outer = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.p3Outer.setObjectName("p3Outer")
        self.p3Desc = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3Desc.sizePolicy().hasHeightForWidth())
        self.p3Desc.setSizePolicy(sizePolicy)
        self.p3Desc.setMinimumSize(QtCore.QSize(0, 70))
        self.p3Desc.setWordWrap(True)
        self.p3Desc.setObjectName("p3Desc")
        self.p3Outer.addWidget(self.p3Desc)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.hvUserNameLbl = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvUserNameLbl.sizePolicy().hasHeightForWidth())
        self.hvUserNameLbl.setSizePolicy(sizePolicy)
        self.hvUserNameLbl.setIndent(20)
        self.hvUserNameLbl.setObjectName("hvUserNameLbl")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.hvUserNameLbl)
        self.hvUserName = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvUserName.sizePolicy().hasHeightForWidth())
        self.hvUserName.setSizePolicy(sizePolicy)
        self.hvUserName.setObjectName("hvUserName")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.hvUserName)
        self.hvPasswordLbl = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvPasswordLbl.sizePolicy().hasHeightForWidth())
        self.hvPasswordLbl.setSizePolicy(sizePolicy)
        self.hvPasswordLbl.setIndent(20)
        self.hvPasswordLbl.setObjectName("hvPasswordLbl")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.hvPasswordLbl)
        self.hvPassword = QtGui.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hvPassword.sizePolicy().hasHeightForWidth())
        self.hvPassword.setSizePolicy(sizePolicy)
        self.hvPassword.setEchoMode(QtGui.QLineEdit.Normal)
        self.hvPassword.setObjectName("hvPassword")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.hvPassword)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtGui.QFormLayout.FieldRole, spacerItem2)
        self.p3Outer.addLayout(self.formLayout_2)
        InstallWizard.addPage(self.wizardPage3)
        self.wizardPage4 = QtGui.QWizardPage()
        self.wizardPage4.setObjectName("wizardPage4")
        self.horizontalLayoutWidget = QtGui.QWidget(self.wizardPage4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 90, 451, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.jp2RootDirLbl = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jp2RootDirLbl.sizePolicy().hasHeightForWidth())
        self.jp2RootDirLbl.setSizePolicy(sizePolicy)
        self.jp2RootDirLbl.setMaximumSize(QtCore.QSize(80, 16777215))
        self.jp2RootDirLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.jp2RootDirLbl.setWordWrap(True)
        self.jp2RootDirLbl.setObjectName("jp2RootDirLbl")
        self.horizontalLayout.addWidget(self.jp2RootDirLbl)
        self.jp2RootDirInput = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.jp2RootDirInput.setObjectName("jp2RootDirInput")
        self.horizontalLayout.addWidget(self.jp2RootDirInput)
        self.jp2BrowseBtn = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jp2BrowseBtn.sizePolicy().hasHeightForWidth())
        self.jp2BrowseBtn.setSizePolicy(sizePolicy)
        self.jp2BrowseBtn.setObjectName("jp2BrowseBtn")
        self.horizontalLayout.addWidget(self.jp2BrowseBtn)
        InstallWizard.addPage(self.wizardPage4)
        self.wizardPage5 = QtGui.QWizardPage()
        self.wizardPage5.setObjectName("wizardPage5")
        self.label = QtGui.QLabel(self.wizardPage5)
        self.label.setGeometry(QtCore.QRect(20, 0, 501, 51))
        self.label.setObjectName("label")
        InstallWizard.addPage(self.wizardPage5)

        self.retranslateUi(InstallWizard)
        QtCore.QMetaObject.connectSlotsByName(InstallWizard)

    def retranslateUi(self, InstallWizard):
        InstallWizard.setWindowTitle(QtGui.QApplication.translate("InstallWizard", "Helioviewer Database Installation", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage1.setTitle(QtGui.QApplication.translate("InstallWizard", "Introduction", None, QtGui.QApplication.UnicodeUTF8))
        self.greetingMsg.setText(QtGui.QApplication.translate("InstallWizard", "This wizard will help setup the required database structure used by the Helioviewer project. We assume that you have an existing database installation (either MySQL or PostgreSQL), and that you have the proper access priveges in order to create new schemas and users in that system. Click \"Next\" to begin!", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage2.setTitle(QtGui.QApplication.translate("InstallWizard", "Database Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage2.setSubTitle(QtGui.QApplication.translate("InstallWizard", "Existing database information", None, QtGui.QApplication.UnicodeUTF8))
        self.p2Desc.setText(QtGui.QApplication.translate("InstallWizard", "Select the type of database you wish to use and the login information for an administrative user in that system", None, QtGui.QApplication.UnicodeUTF8))
        self.dbTypeLbl.setText(QtGui.QApplication.translate("InstallWizard", "Database type:", None, QtGui.QApplication.UnicodeUTF8))
        self.dbadminUserNameLbl.setText(QtGui.QApplication.translate("InstallWizard", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("InstallWizard", "MySQL", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2.setText(QtGui.QApplication.translate("InstallWizard", "PostgreSQL", None, QtGui.QApplication.UnicodeUTF8))
        self.dbadminPasswordLbl.setText(QtGui.QApplication.translate("InstallWizard", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage3.setTitle(QtGui.QApplication.translate("InstallWizard", "Database Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage3.setSubTitle(QtGui.QApplication.translate("InstallWizard", "New database information", None, QtGui.QApplication.UnicodeUTF8))
        self.p3Desc.setText(QtGui.QApplication.translate("InstallWizard", "Please select a username and password to use for the Helioviewer database:", None, QtGui.QApplication.UnicodeUTF8))
        self.hvUserNameLbl.setText(QtGui.QApplication.translate("InstallWizard", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.hvUserName.setText(QtGui.QApplication.translate("InstallWizard", "helioviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.hvPasswordLbl.setText(QtGui.QApplication.translate("InstallWizard", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.hvPassword.setText(QtGui.QApplication.translate("InstallWizard", "helioviewer", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage4.setTitle(QtGui.QApplication.translate("InstallWizard", "Image Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage4.setSubTitle(QtGui.QApplication.translate("InstallWizard", "JPEG 2000 Image Archive Location", None, QtGui.QApplication.UnicodeUTF8))
        self.jp2RootDirLbl.setText(QtGui.QApplication.translate("InstallWizard", "JP2 Archive Location:", None, QtGui.QApplication.UnicodeUTF8))
        self.jp2RootDirInput.setText(QtGui.QApplication.translate("InstallWizard", "/var/www/jp2", None, QtGui.QApplication.UnicodeUTF8))
        self.jp2BrowseBtn.setText(QtGui.QApplication.translate("InstallWizard", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.wizardPage5.setTitle(QtGui.QApplication.translate("InstallWizard", "Finished!", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("InstallWizard", "You have successfully installed the Helioviewer database.", None, QtGui.QApplication.UnicodeUTF8))

import resources.hv_rc
