<?php
/* vim: set expandtab tabstop=4 shiftwidth=4 softtabstop=4: */
/**
 * SSW Helioviewer.org Script Generator
 *
 * PHP version 5
 *
 * @category Helper
 * @package  Helioviewer
 * @author   Keith Hughitt <keith.hughitt@nasa.gov>
 * @license  http://www.mozilla.org/MPL/MPL-1.1.html Mozilla Public License 1.1
 * @link     http://launchpad.net/helioviewer.org
 *
 */
function createSSWScript($observatory, $instrument, $detector, $measurement, $movieId=null) {
    $filename = _getSSWScriptFilename();
    $provenance = _getSSWProvenanceComment($movieId);

    $code = <<<EOD
;
; Solarsoft data download script $filename
;
; NOTE: this script may make use of the SDO cutout service called via
; a Solarsoft command. To use this command properly, you MUST edit
; the email keyword of the "ssw_cutout_service" command to provide the
; command with YOUR email address.
;
;
; (1) Helioviewer provenance information
; --------------------------------------
; $provenance
;
; (2) The Solarsoft environment and commands used to find and acquire data
; ------------------------------------------------------------------------
;
; This script requires an up-to-date installation of Solarsoft with
; the ONTOLOGY package installed. Solarsoft requires that you have
; access to an installation of IDL.
;
; This script is provided AS-IS. NOTE: It may require editing for it to
; work on your local system. Also, many of the commands included here
; have more sophisticated options that can be used to optimize your ability
; to acquire the relevant data. Please consult the relevant documentation
; for further information.
;
; To find out more about acquiring solar data, please consult
; the following links are useful:
;
; Installing and upgrading Solarsoft
; http://www.lmsal.com/solarsoft/ssw_install_howto.html
;
; SDO data analysis, Solarsoft, VSO and AIA cutout service
; https://www.lmsal.com/sdodocs/doc/dcur/SDOD0060.zip/zip/entry/
;
; VSO
; http://docs.virtualsolar.org/wiki/VsoIDL/VsoSearch
;
; The commands
;
; IDL> doc_menu,<IDL program name>
;
; or
;
; IDL> xdoc
;
; can also be used to find out more about each command in the script below.
;
;
; (3) Executing the script
; ------------------------
;
; To run this script, place it in a directory that your IDL session is
; aware of and type
;
; IDL> .run solarsoft_helioviewer_data_script_AIA_EIT_LASCO-C2_20120716_120354__20120716_140354.pro
;
; or pre-prend the script with a path to the script, for example,
;
; IDL> .run path/to/script/solarsoft_helioviewer_data_script_AIA_EIT_LASCO-C2_20120716_120354__20120716_140354.pro
;
; Data will be downloaded to your current working directory.
;
;
; (4) Script
; ----------
;
; Search for data in the following date time range
;
tstart = '2012-07-16 12:03:54'
tend = '2012-07-16 14:03:54'

;
; EIT data - downloadable via the VSO
;
a_eit = vso_search(tstart, tend, inst = 'EIT', wave = '304')
b_eit = vso_get( a_eit )

;
; LASCO-C2 data - downloadable via the VSO
;
a_lascoc2 = vso_search(tstart, tend, instrument = 'LASCO', detector = 'C2')
b_lascoc2 = vso_get( a_lascoc2 )

;
; AIA data - downloadable via the SDO cutout service or the VSO.
;
; Helioviewer.org has detected that the movie you made contains a
; partial view of AIA or HMI data. The commands below spawn a request
; to the SDO data cutout service to download only those SDO data in
; the field of view of the movie you made. A script to download the
; full disk SDO data via the VSO is also included below.
;
; The cutout service will notify you by EMAIL when your request is ready.
; PLEASE EDIT THE COMMAND BELOW TO INCLUDE YOUR EMAIL ADDRESS.
;
; AIA data - using the SDO cutout service
;
ssw_cutout_service,tstart,tend,$
 ref_helio='[centroid coordinates]',$
 fovx=width_in_pixels,fovy=height_in_pixels,$
 waves=193,$
 instr='AIA',$
 email='xxx@yyy.zzz'

;
; AIA data - downloadable via the VSO
;
; Optional: download the full disk SDO via the VSO. Remove the comments
; to download full disk SDO data
;
; a_aia = vso_search(tstart, tend, instrument = 'AIA', wave = '193')
; b_aia = vso_get( a_aia )

;
; (5) Script ends
; ---------------
;
END
EOD;

_printSSWScript($filename, $code);
}

/**
 * @TODO ex. solarsoft_helioviewer_data_script_AIA_EIT_LASCO-C2_20120716_120354__20120716_140354.pro
 */
function _getSSWScriptFilename() {
    return "solarsoft_helioviewer_data_script.pro";
}

function _getSSWProvenanceComment($movieId) {
    require_once "src/Helper/DateTimeConversions.php";

    $now = getUTCDateString();
    
    $comment = "Automatically generated by Helioviewer.org on $now.\n" .
               "; This script uses the Virtual Solar Observatory (VSO) and SDO cutout\n" .
               "; service ";
               
    // Movie id?
    if (!is_null($movieId)) {
        $comment .= "to download the original science data  used to generate\n" .
                    "; the Helioviewer.org movie http://www.helioviewer.org/?movieid=$moveId\n;";
    } else {
        $comment .= "to download original science data.\n;";
    }

    return $comment;
}

function _getSSWEITSnippet() {
    
}

function _getSSWLASCOSnippet() {
    
}

function _getSSWAIASnippet() {
    
}

/**
 * Returns generated script as a file attachment
 */
function _printSSWScript($filename, $body) {
    // Set HTTP headers
    header("Pragma: public");
    header("Expires: 0");
    header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
    header("Cache-Control: private", false); // required for certain browsers
    header("Content-Disposition: attachment; filename=\"" . $filename . "\"");
    header("Content-Transfer-Encoding: binary");
    header("Content-Length: " . mb_strlen($body));
    header("Content-type: image/png");
    
    echo $body;
}

?>