name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install node dependencies
      run: npm ci

    - name: Prettier check (tests and certain files)
      run: npm run prettier-check

  jest-unit-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Setup java for access to `ant`
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install node dependencies
      run: npm ci

    - name: Test building with ant
      run: |
        cd resources/build && ant && cd ..

    - name: Run js unit tests
      run: npm run test
  playwright-e2e-tests:
    strategy:
      matrix:
        shardIndex: [1, 2, 3, 4, 5]
        shardTotal: [5]
      # If one of the shards fails, continue running the remaining tests
      fail-fast: false

    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Run Playwright tests
      uses: Helioviewer-Project/helioviewer.org-tests/.github/actions/playwright-test@main
      with:
        api-ref: ${{ github.sha }}
        shard-index: ${{ matrix.shardIndex }}
        shard-total: ${{ matrix.shardTotal }}
  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: ${{ !cancelled() }}
    needs: [playwright-e2e-tests]

    runs-on: ubuntu-latest
    steps:
    - name: Checkout test code
      uses: actions/checkout@v4
      with:
        repository: 'Helioviewer-Project/helioviewer.org-tests'
        path: 'helioviewer.org-tests'

    - name: Merge Playwright reports
      uses: Helioviewer-Project/helioviewer.org-tests/.github/actions/playwright-merge-reports@main
      with:
        test-repo-path: 'helioviewer.org-tests'
