name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x']

    steps:
    - uses: actions/checkout@v3
    # Setup java for access to `ant`
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install node dependencies
      run: npm ci

    - name: Test building with ant
      run: |
        cd resources/build && ant && cd ..

    - name: Run js unit tests
      run: npm run test
